### ISSUE TITLE
auto login system

### ISSUE THREAD

**Issue by khoiphan21** [khoiphan21/sourcestash#3]
# User Story
As a **user**, I want **the app to automatically log in the second time if i tell it to do so** 
# Task
- [x] creating a **auto login** system when the user try to log in the 2nd time

**Comment by jeremyng5352** [comment]
# User Story
As a USER, I want THE APP TO AUTOMATICALLY LOG IN THE SECOND TIME IF I TELL IT TO DO SO
# Task
creating a AUTO LOGIN system when the user try to log in the 2nd time
